name: Build MP4Box (Mini Build) for Windows (MSVC 14)

on:
  push:
    branches:
      - main  # 可以根据需要指定其他分支

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 提供的最新 Windows 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 拉取最新的代码

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1  # 配置 Visual Studio 环境
        with:
          vs-version: '2019'  # 或指定其他版本，如 2017（MSVC 14 即为 2015 版）

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'  # 安装 CMake

      - name: Build MP4Box using MSVC
        run: |
          cd gpac  # 进入到 GPAC 项目根目录
          mkdir build
          cd build
          # 使用 MSVC 14 编译 GPAC，指定使用 msvc14 的 CMake 配置
          cmake ..\build\msvc14 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Create ZIP for release
        run: |
          mkdir release
          copy build/MP4Box/Release/MP4Box.exe release/
          cd release
          zip mp4box-win.zip MP4Box.exe

      - name: Upload release ZIP
        uses: actions/upload-artifact@v3
        with:
          name: mp4box-win
          path: release/mp4box-win.zip
